// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wait

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWaiter creates a new instance of Waiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWaiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Waiter {
	mock := &Waiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Waiter is an autogenerated mock type for the Waiter type
type Waiter struct {
	mock.Mock
}

type Waiter_Expecter struct {
	mock *mock.Mock
}

func (_m *Waiter) EXPECT() *Waiter_Expecter {
	return &Waiter_Expecter{mock: &_m.Mock}
}

// Wait provides a mock function for the type Waiter
func (_mock *Waiter) Wait(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Waiter_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type Waiter_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Waiter_Expecter) Wait(ctx any) *Waiter_Wait_Call {
	return &Waiter_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *Waiter_Wait_Call) Run(run func(ctx context.Context)) *Waiter_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Waiter_Wait_Call) Return(err error) *Waiter_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Waiter_Wait_Call) RunAndReturn(run func(ctx context.Context) error) *Waiter_Wait_Call {
	_c.Call.Return(run)
	return _c
}
