# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - intrange
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - rowserrcheck
    - tagliatelle
    - tenv
    - testpackage
    - testifylint
    - varnamelen
    - wastedassign
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - err113
        - funlen
        - goconst
        - mnd
        - noctx
      path: "_test.go"
